### ISSUE TITLE
PRNG Parameters

### ISSUE THREAD

**Issue by mehmetemingulsen** [fsssosei/Pure_PRNG#2]
Firstly, thanks for the great work. I have a question. It is actually not an issue but I couldn't find the parameters of the PRNGs. For instance, if we consider QCG with the following formula x_{i+1} = a.x_{i}^2 mod m, what is the value of a or m or the seed ? Thanks

**Comment by fsssosei** [comment]
If you customize the formula, the formula parameters should be written in the program.

By the way, the interface will change a lot in the next big release.
